Add alicloud_kms_secret table. Closes #10
turbot/steampipe-plugin-alicloud pull request #11
Opened 2021-02-18 14:11 UTC by rajeshbal65

2021-03-02 07:07 UTC, Subhajit97 commented on alicloud/service.go
> +// VpcService returns the service connection for Alicloud VPC service
```suggestion
// KMSService returns the service connection for Alicloud Key Management Service
```

2021-03-02 07:09 UTC, Subhajit97 commented on alicloud/table_alicloud_kms_secret.go
> +				// Hydrate:     getKmsSecret,
```suggestion
```

2021-03-02 07:09 UTC, Subhajit97 commented on alicloud/table_alicloud_kms_secret.go
> +				Description: "To be update",
Fix column description

2021-03-02 07:11 UTC, Subhajit97 commented on alicloud/table_alicloud_kms_secret.go
> +			// alicloud standard columns
Add `region` column

2021-03-02 07:11 UTC, Subhajit97 commented on alicloud/table_alicloud_kms_secret.go
> +
```suggestion

//// LIST FUNCTION

```

2021-03-02 07:12 UTC, Subhajit97 commented on alicloud/table_alicloud_kms_secret.go
> +
```suggestion

//// HYDRATE FUNCTIONS

```

2021-03-02 07:12 UTC, Subhajit97 commented on alicloud/table_alicloud_kms_secret.go
> +	// panic(name)
```suggestion
```

2021-03-02 08:36 UTC, Subhajit97 requested changes
Please make suggested changes, and also add docs

2021-03-10 22:43 UTC, cbruno10 commented on docs/tables/alicloud_kms_secret.md
> +### Get the rotation info for each secret
@rajeshbal65 Can you please add 2 example queries based on the following descriptions:
`List keys that do not have automatic rotation enabled`
`List keys that have not been rotated within the last 30 days`

2021-03-10 22:43 UTC, cbruno10 requested changes
Please see comments, thanks!

2021-03-16 20:03 UTC, cbruno10 approved these changes

2021-03-16 20:03 UTC, merged