Query is breaking for security_ip_list. closes#114
turbot/steampipe-plugin-alicloud pull request #117
Opened 2021-03-15 10:27 UTC by bigdatasourav

2021-03-15 10:27 UTC, bigdatasourav commented
> select security_ip_list,db_instance_id from alicloud_rds_instance where db_instance_id = 'rm-7go155igl16ty92n9'
+------------------+----------------------+
| security_ip_list | db_instance_id       |
+------------------+----------------------+
| 127.0.0.1        | rm-7go155igl16ty92n9 |

2021-03-15 12:59 UTC, bigdatasourav commented
> select jsonb_pretty(ip_array_list) as ip_details from alicloud_rds_instance where db_instance_id = 'rm-7gosgb525264xb5j8'
+---------------------------------------------------------------------------------------------------------------------------------+
| ip_details                                                                                                                      |
+---------------------------------------------------------------------------------------------------------------------------------+
| [                                                                                                                               |
|     {                                                                                                                           |
|         "SecurityIPList": "127.0.0.1",                                                                                          |
|         "SecurityIPType": "IPv4",                                                                                               |
|         "WhitelistNetworkType": "MIX",                                                                                          |
|         "DBInstanceIPArrayName": "default",                                                                                     |
|         "DBInstanceIPArrayAttribute": ""                                                                                        |
|     },                                                                                                                          |
|     {                                                                                                                           |
|         "SecurityIPList": "100.104.106.0/24,100.104.160.192/26,100.104.188.0/24,11.59.10.2,11.59.10.3,11.59.6.125,11.59.6.126", |
|         "SecurityIPType": "IPv4",                                                                                               |
|         "WhitelistNetworkType": "MIX",                                                                                          |
|         "DBInstanceIPArrayName": "hdm_security_ips",                                                                            |
|         "DBInstanceIPArrayAttribute": "hidden"                                                                                  |
|     },                                                                                                                          |
|     {                                                                                                                           |
|         "SecurityIPList": "0.0.0.0/0",                                                                                          |
|         "SecurityIPType": "IPv4",                                                                                               |
|         "WhitelistNetworkType": "MIX",                                                                                          |
|         "DBInstanceIPArrayName": "inbound_internet",                                                                            |
|         "DBInstanceIPArrayAttribute": ""                                                                                        |
|     }                                                                                                                           |
| ]                                                                                                                               |

2021-03-15 16:21 UTC, cbruno10 commented on alicloud/table_alicloud_rds_instance.go
> +				Name:        "ip_array_list",
Can you please rename this to `security_ips_src`? In this column, we should not modify any of the fields, even the `SecurityIPList` field, which is a comma delimited list of IPs.

2021-03-15 16:22 UTC, cbruno10 commented on alicloud/table_alicloud_rds_instance.go
> +				Name:        "ip_array_list",
We should also add a column called `security_ips` that's a list of strings, which is composed of the addresses from the `SecurityIPList` fields.

2021-03-15 16:25 UTC, cbruno10 requested changes
Please see comments on column changes, thanks!

2021-03-16 07:23 UTC, bigdatasourav commented
```
> select security_ips,security_ips_src,db_instance_id from alicloud_rds_instance
+--------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------
| security_ips                                                                                                                   | security_ips_src                                                         
+--------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------
| ["127.0.0.1","100.104.106.0/24,100.104.160.192/26,100.104.188.0/24,11.59.10.2,11.59.10.3,11.59.6.125,11.59.6.126","0.0.0.0/1"] | [{"DBInstanceIPArrayAttribute":"","DBInstanceIPArrayName":"default","Secu
| ["127.0.0.1","100.104.106.0/24,100.104.160.192/26,100.104.188.0/24,11.59.10.2,11.59.10.3,11.59.6.125,11.59.6.126","0.0.0.0/0"] | [{"DBInstanceIPArrayAttribute":"","DBInstanceIPArrayName":"default","Secu
+--------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------
> select security_ips,security_ips_src,db_instance_id from alicloud_rds_instance where db_instance_id='rm-7go155igl16ty92n9'
+--------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------
| security_ips                                                                                                                   | security_ips_src                                                         
+--------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------
| ["127.0.0.1","100.104.106.0/24,100.104.160.192/26,100.104.188.0/24,11.59.10.2,11.59.10.3,11.59.6.125,11.59.6.126","0.0.0.0/1"] | [{"DBInstanceIPArrayAttribute":"","DBInstanceIPArrayName":"default","Secu
+--------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------
> ```

2021-03-16 20:30 UTC, cbruno10 commented
@bigdatasourav In the example output above, can you please edit to include a non-truncated version?

Also, can you please replace the example you have in the doc with a query for:
`### List DB instances that allow 0.0.0.0/0 `

2021-03-16 20:30 UTC, cbruno10 requested changes
Please see PR comment, thanks!

2021-03-17 12:47 UTC, bigdatasourav commented
```
> select db_instance_id, security_ips from alicloud_rds_instance where security_ips :: jsonb ? '0.0.0.0/0'
+----------------------+--------------------------------------------------------------------------------------------------------------------------------+
| db_instance_id       | security_ips                                                                                                                   |
+----------------------+--------------------------------------------------------------------------------------------------------------------------------+
| rm-7goaou30dq55i7p65 | ["127.0.0.1","100.104.106.0/24,100.104.160.192/26,100.104.188.0/24,11.59.10.2,11.59.10.3,11.59.6.125,11.59.6.126","0.0.0.0/0"] |
+----------------------+--------------------------------------------------------------------------------------------------------------------------------+
>

2021-03-17 21:26 UTC, cbruno10 approved these changes

2021-03-17 21:52 UTC, cbruno10 approved these changes

2021-03-17 22:03 UTC, merged