Add vpc_flow_log table. closes #103
turbot/steampipe-plugin-alicloud pull request #127
Opened 2021-03-22 07:58 UTC by bigdatasourav

2021-03-22 08:04 UTC, bigdatasourav commented
as discussed -
```
Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_vpc_flow_log.go:126: Resource alicloud_vpc_flow_log CreateFlowLog Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
SDKError:
   Code: OperationUnsupported.actionError
   Message: code: 400, This action is not support. requestid: FAF4CBA6-357C-4A19-94F8-B78F4B9D6B97
   Data: {"Code":"OperationUnsupported.action","HostId":"vpc.aliyuncs.com","Message":"This action is not support.","Recommend":"https://error-center.aliyun.com/status/search?Keyword=OperationUnsupported.action\u0026source=PopGw","RequestId":"FAF4CBA6-357C-4A19-94F8-B78F4B9D6B97"}

2021-03-24 14:42 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_flow_log.go
> +	}
Do we need this check?

2021-03-24 14:43 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_flow_log.go
> +	// Get project details
Add new line before comment
```suggestion
	
	// Get project details
```

2021-03-24 14:44 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_flow_log.go
> +//// TRANSFORM FUNCTIONS
```suggestion
```

2021-03-24 14:44 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_flow_log.go
> +
```suggestion

//// TRANSFORM FUNCTIONS

```

2021-03-24 14:44 UTC, Subhajit97 commented on docs/tables/alicloud_vpc_flow_log.md
> +### List flow logs where resource type is VPC.
```suggestion
### List flow logs where resource type is VPC
```

2021-03-24 14:45 UTC, Subhajit97 commented on alicloud-test/tests/alicloud_vpc_flow_log/variables.tf
> +
```suggestion
```

2021-03-24 14:46 UTC, Subhajit97 commented on alicloud-test/tests/alicloud_vpc_flow_log/variables.tf
> +  name       = var.resource_name
From alicloud provider `1.119.0`, `name` attribute is deprecated.
Use `vpc_name` instead.
```suggestion
  vpc_name       = var.resource_name
```

2021-03-24 14:47 UTC, Subhajit97 commented on alicloud-test/tests/alicloud_vpc_flow_log/variables.tf
> +}
Can't we pass these values directly in `alicloud_vpc_flow_log` plan?

2021-03-24 14:55 UTC, Subhajit97 requested changes
@bigdatasourav Can you please remove `package-lock.json` file change from this commit?
Make suggested changes, and also add the add the outputs of the queries added in docs.

2021-03-30 10:08 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_flow_log.go
> +		plugin.Logger(ctx).Warn("alicloud_vpc.listVpc", "item", i)
```suggestion
```

2021-03-30 10:10 UTC, Subhajit97 commented on alicloud/plugin.go
>  			"alicloud_ecs_key_pair":             tableAlicloudEcskeyPair(ctx),
Sort the list

2021-03-30 10:12 UTC, Subhajit97 requested changes
@bigdatasourav There are few changes required. Please see comments.
Also can you please add the outputs of the example queries?

2021-04-23 12:42 UTC, cbruno10 commented
Closing PR as this feature is currently blocked, will re-open once it's ready.

2021-04-23 12:42 UTC, closed without merging