Add column arn for the table alicloud_ecs_instance. Closes #142
turbot/steampipe-plugin-alicloud pull request #151
Opened 2021-06-02 12:39 UTC by rajeshbal65

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2021-06-03 07:10 UTC, Subhajit97 commented on alicloud/table_alicloud_ecs_instance.go
> +				Transform:   transform.FromValue().Transform(ensureStringArray),
```suggestion
				Transform:   transform.FromValue().Transform(transform.EnsureStringArray),
```

2021-06-03 07:10 UTC, Subhajit97 commented on alicloud/table_alicloud_ecs_instance.go
> +func getEcsInstanceArn(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func getEcsInstanceARN(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```

2021-06-03 07:12 UTC, Subhajit97 requested changes
@rajeshbal65 Please see comments, thanks!
Can you also add the integration test to validate the `arn` column?

2021-06-09 11:42 UTC, Subhajit97 approved these changes
LGTM

2021-06-09 15:38 UTC, cbruno10 approved these changes

2021-06-09 15:41 UTC, merged