Add column arn for the table alicloud_rds_instance. Closes #147
turbot/steampipe-plugin-alicloud pull request #156
Opened 2021-06-02 13:13 UTC by rajeshbal65

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2021-06-07 15:07 UTC, bigdatasourav commented on alicloud/table_alicloud_rds_instance.go
> +				Name:        "sql_collector_status",
the column name will be audit_status

2021-06-07 15:08 UTC, bigdatasourav commented on alicloud/table_alicloud_rds_instance.go
> +				Description: "The log backup retention duration that is allowed by the SQL explorer feature on the instance.",
The audit retention duration that is allowed by the SQL explorer feature on the instance.

2021-06-07 15:12 UTC, bigdatasourav commented on alicloud/table_alicloud_rds_instance.go
> +			plugin.Logger(ctx).Warn("alicloud_rds.DescribeDBInstancesxxxxxxxxx", "item", i)
provide proper message

2021-06-07 15:12 UTC, bigdatasourav commented on alicloud/table_alicloud_rds_instance.go
> +		if serverErr.ErrorCode() == "InstanceEngineType.NotSupport" {
should have InvalidDBInstanceId.NotFound or InvalidDBInstanceId.NotFound

2021-06-07 15:27 UTC, bigdatasourav commented on alicloud/table_alicloud_rds_instance.go
> +	return "acs:rds:" + region + ":" + accountID + ":instance/" + instanceID, nil
check the arn format once - it should be -arn:acs:dds:cn-hangzhou:123456789xxxxxxx:instance/dds-uf6ab1exxxx

2021-06-07 15:29 UTC, bigdatasourav commented on alicloud/table_alicloud_rds_instance.go
> +	request.DBInstanceId = databaseID(h.Item)
DBInstanceId set twice

2021-06-07 15:31 UTC, bigdatasourav commented on alicloud/table_alicloud_rds_instance.go
> +	request.DBInstanceId = databaseID(h.Item)
DBInstanceId set twice

2021-06-07 15:31 UTC, bigdatasourav commented
@rajeshbal65 plz resolve.

2021-06-08 15:17 UTC, Subhajit97 commented on alicloud/table_alicloud_rds_instance.go
> +	return "acs:acs:rds:" + region + ":" + accountID + ":instance/" + instanceID, nil
```suggestion
	return "arn:acs:rds:" + region + ":" + accountID + ":instance/" + instanceID, nil
```

2021-06-08 15:19 UTC, Subhajit97 requested changes
@rajeshbal65 There is a small change required in `arn` format. Please see comments, thanks!

2021-06-09 15:12 UTC, Subhajit97 approved these changes
LGTM

2021-06-10 05:13 UTC, bigdatasourav approved these changes
LGTM

2021-06-10 12:33 UTC, cbruno10 approved these changes

2021-06-10 12:34 UTC, merged