Add table alicloud_rds_instance_metric_cpu_utilization closes #209
turbot/steampipe-plugin-alicloud pull request #214
Opened 2021-07-26 10:49 UTC by ParthaI

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2021-07-28 11:37 UTC, Subhajit97 commented on alicloud/table_alicloud_rds_instance_metric_cpu_utilizations.go
> +package alicloud
@ParthaI can you please rename the file to 
`table_alicloud_rds_instance_metric_cpu_utilization`?

2021-07-28 11:53 UTC, Subhajit97 requested changes
@ParthaI Please see comments, thanks!

2021-07-29 06:56 UTC, Subhajit97 approved these changes

2021-07-29 07:41 UTC, rajlearner17 approved these changes
LGTM

2021-07-29 07:49 UTC, merged