Add table vpc_nat_gateway. Closes #25
turbot/steampipe-plugin-alicloud pull request #28
Opened 2021-02-22 10:13 UTC by rajeshbal65

2021-03-02 11:33 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_nat_gateway.go
> +				// Transform:   transform.FromField("ForwardTableIds.ForwardTableId"),
```suggestion
```

2021-03-10 21:43 UTC, cbruno10 commented on docs/tables/alicloud_vpc_nat_gateway.md
> +### Count of NAT gateway per VPC id
Based on the description, I don't think this query is grouping them properly. Can you please review this one?

2021-03-10 21:43 UTC, cbruno10 commented on docs/tables/alicloud_vpc_nat_gateway.md
> +### Get the NAT gateway where deletion protection is not enabled
Please change this description to `List NAT gateways that have deletion protection disabled`

2021-03-10 21:44 UTC, cbruno10 commented on docs/tables/alicloud_vpc_nat_gateway.md
> +### Get the NAT gateway where traffic monitoring feature is not enabled
Please change this description to `List NAT gateways that have traffic monitoring disabled`

2021-03-10 21:45 UTC, cbruno10 commented on docs/tables/alicloud_vpc_nat_gateway.md
> +  nat_gateway_private_info ->> 'MaxBandwidth' as eni_instance_id,
Is this correct? Seems like a mismatch

2021-03-10 21:45 UTC, cbruno10 commented on docs/tables/alicloud_vpc_nat_gateway.md
> +### Get the Private network info of NAT gateway
Please change this description to `List private network info for NAT gateways`

2021-03-10 21:46 UTC, cbruno10 commented on docs/tables/alicloud_vpc_nat_gateway.md
> +### IP address details of the NAT gateway
Please change this description to `List IP address details for NAT gateways`

2021-03-10 21:49 UTC, cbruno10 commented on docs/tables/alicloud_vpc_nat_gateway.md
> +## Examples
Are there any examples we can add around checking NAT gateways that will expire in the next 30 days, or if they're only in 1 zone (this one would make more sense depending on what best practice is, e.g., NAT gateways should be in at least 2 zones)?

2021-03-10 21:49 UTC, cbruno10 requested changes
Please see review comments, thanks!

2021-03-16 20:07 UTC, cbruno10 approved these changes

2021-03-16 20:08 UTC, merged