Add table for VPC Network ACL. Closes #41
turbot/steampipe-plugin-alicloud pull request #48
Opened 2021-02-23 13:53 UTC by rajeshbal65

2021-03-05 15:59 UTC, Subhajit97 commented on alicloud/plugin.go
> +			"alicloud_vpc_network_acl":         tableAlicloudVpcNetworkAcl(ctx),
Sort the list

2021-03-05 15:59 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_network_acl.go
> +		Description: "VPC network ACL.",
```suggestion
		Description: "Alicloud VPC Network ACL.",
```

2021-03-05 16:02 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_network_acl.go
> +				Description: "The ID of the associated VPC.",
Fix `vpc_id` column
```suggestion
				Name:        "vpc_id",
				Type:        proto.ColumnType_STRING,
				Description: "The ID of the associated VPC.",
```

2021-03-05 16:02 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_network_acl.go
> +				Description: "The ID of the associated VPC.",
![image](https://user-images.githubusercontent.com/38218418/110140654-536ed300-7dfa-11eb-9052-2a08c5327d63.png)

2021-03-05 16:03 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_network_acl.go
> +			// steampipe standard columns
```suggestion
			
			// steampipe standard columns
```

2021-03-05 16:04 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_network_acl.go
> +			},
Add `tags_src` column

2021-03-05 16:04 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_network_acl.go
> +			// alicloud standard columns
```suggestion
			
			// alicloud standard columns
```

2021-03-05 16:05 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_network_acl.go
> +				Transform:   transform.FromField("NetworkAclName"),
Add `NetworkAclId` as fallback value for `title`, if `NetworkAclName` is null.

2021-03-05 16:05 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_network_acl.go
> +				Transform:   transform.FromField("NetworkAclId"),
```suggestion
```

2021-03-05 16:06 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_network_acl.go
> +
```suggestion

//// LIST FUNCTION

```

2021-03-05 16:06 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_network_acl.go
> +	count := 0
```suggestion
	
	count := 0
```

2021-03-05 16:06 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_network_acl.go
> +		for _, NetworkAcl := range response.NetworkAcls.NetworkAcl {
Use lowerCamelCase
```suggestion
		for _, networkAcl := range response.NetworkAcls.NetworkAcl {
```

2021-03-05 16:07 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_network_acl.go
> +
```suggestion

//// HYDRATE FUNCTIONS

```

2021-03-05 16:09 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_network_acl.go
> +		}
Use `ShouldIgnoreError` for `notFound` cases.

2021-03-05 16:09 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_network_acl.go
> +	plugin.Logger(ctx).Trace("getEcsDiskAka")
```suggestion
	plugin.Logger(ctx).Trace("getNetworkAclAka")
```

2021-03-05 16:10 UTC, Subhajit97 commented on alicloud/table_alicloud_vpc_network_acl.go
> +				Transform:   transform.FromField("AccountID"),
Do we need `getCommonColumns` for `account_id`?
Or, we can use the value of `owner_id` column?

2021-03-05 16:12 UTC, Subhajit97 requested changes
Make suggested changes, and also add docs and tests.

2021-03-18 13:07 UTC, cbruno10 commented
Closing this PR for now (but keeping branch), as this table is still under development.

2021-03-24 14:36 UTC, Subhajit97 submitted a review, later dismissed
LGTM

2021-03-24 20:21 UTC, cbruno10 approved these changes

2021-03-24 20:21 UTC, merged