Add alicloud_kms_key table. Closes #6
turbot/steampipe-plugin-alicloud pull request #7
Opened 2021-02-18 12:01 UTC by rajeshbal65

2021-03-02 06:25 UTC, Subhajit97 commented on alicloud/table_alicloud_kms_key.go
> +				Description: "The globally unique ID of the CMK."},
```suggestion
				Description: "The globally unique ID of the CMK.",
			},
```

2021-03-02 06:35 UTC, Subhajit97 commented on alicloud/table_alicloud_kms_key.go
> +			// alicloud standard columns
```suggestion
			// alicloud standard columns
						{
				Name:        "region",
				Description: ColumnDescriptionRegion,
				Type:        proto.ColumnType_STRING,
                                  // Required transform to fetch the region
			},
```

2021-03-02 06:37 UTC, Subhajit97 commented on alicloud/table_alicloud_kms_key.go
> +			},
Modify the `tags_src`.
The value should be as following
```
[{"TagKey":"acs:ecs:disk-encryption","TagValue":"true"},{"TagKey":"foo","TagValue":"bar"}]
```

2021-03-02 06:39 UTC, Subhajit97 commented on alicloud/table_alicloud_kms_key.go
> +				Description: ColumnDescriptionTags,
Add transform to map the resource tags.
The value should be as following
```
{"acs:ecs:disk-encryption":"true","foo":"bar"}
```

2021-03-02 06:40 UTC, Subhajit97 commented on alicloud/table_alicloud_kms_key.go
> +				Description: "The ID o",
```suggestion
				Description: "The ID of the current primary key version of the symmetric CMK.",
```

2021-03-02 06:42 UTC, Subhajit97 commented on alicloud/table_alicloud_kms_key.go
> +
```suggestion

//// LIST FUNCTION
```

2021-03-02 06:43 UTC, Subhajit97 commented on alicloud/table_alicloud_kms_key.go
> +	client, err := KMSService(ctx, d, region)
```suggestion
	// Create service connection
	client, err := KMSService(ctx, d, region)
```

2021-03-02 06:44 UTC, Subhajit97 commented on alicloud/table_alicloud_kms_key.go
> +
```suggestion

//// HYDRATE FUNCTIONS

```

2021-03-02 06:54 UTC, Subhajit97 commented on alicloud/table_alicloud_kms_key.go
> +			},
```suggestion
			{
				Name:        "key_aliases",
				Description: "A list of aliases bound to a CMK.",
				Type:        proto.ColumnType_JSON,
				Hydrate:     getKeyAlias,
				Transform: transform.FromField("Aliases.Alias"),
			},
```

2021-03-02 06:55 UTC, Subhajit97 commented on alicloud/table_alicloud_kms_key.go
> +	}
```suggestion
	if response.Aliases.Alias != nil {
		return response.Aliases.Alias, nil
	}
```

2021-03-02 06:57 UTC, Subhajit97 requested changes
Please make suggested changes, and also add the docs.

2021-03-10 22:34 UTC, cbruno10 approved these changes

2021-03-10 22:35 UTC, merged